# Generated by Django 3.2.9 on 2021-12-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bens',
            options={'ordering': ['tombamento'], 'verbose_name_plural': 'Bens'},
        ),
        migrations.AlterField(
            model_name='situcoesusobem',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
