# Generated by Django 3.2.9 on 2021-12-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sume', '0002_auto_20211212_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bens',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
